version: '3.8'

services:
  api:
    container_name: "system4Blue-api"
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    image: system4blue/api
    ports:
      - 3333:3333
    networks:
      backend:

  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: systemblue
      MYSQL_DATABASE: systemblue
      MYSQL_USER: systemblue
      MYSQL_PASSWORD: systemblue
    volumes:
        - ./data/mysql:/var/lib/mysql
    networks:
      backend:

  db_admin:
    image: adminer
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8080:8080
    networks:
      backend:

networks:
  backend:
    name: backend
    driver: bridge
